# Generated by Django 5.2.15 on 2026-07-05 17:57

import core.utils
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=core.utils.jalali_now),
        ),
    ]
